DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Bid;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS Item (
    ItemID INTEGER primary key,
    Name VARCHAR(32) DEFAULT NULL,
    Currently INTEGER DEFAULT 0,
    First_Bid INTEGER DEFAULT 0,
    Number_Of_Bids INTEGER DEFAULT 0,
    Started DATETIME  DEFAULT NULL,
    Ends DATETIME DEFAULT NULL,
    SellerID INTEGER DEFAULT 0,
    Description text DEFAULT NULL,
    FOREIGN KEY (SellerID) REFERENCES Users(UserID)   
);

CREATE TABLE IF NOT EXISTS Bid (
    ItemID INTEGER,
    BidderID INTEGER DEFAULT 0,
    BidTime VARCHAR(32) DEFAULT NULL,
    Amount INTEGER DEFAULT 0,
    FOREIGN KEY (BidderID) REFERENCES Users(UserID)
);

CREATE TABLE IF NOT EXISTS Category (
    ItemID INTEGER,
    Category_Name VARCHAR(32) DEFAULT NULL,
    PRIMARY KEY (ItemID, Category_Name),
    FOREIGN KEY (ItemID) REFERENCES Item(ItemID)
);

CREATE TABLE IF NOT EXISTS Users (
    UserID VARCHAR(32) primary key DEFAULT NULL,
    Rating INTEGER DEFAULT 0,
    Location text DEFAULT NULL,
    Country_Code INTEGER DEFAULT NULL
);

